[Book.1]
name = "Beyond Entrepreneurship 2.0"
author = "James C. Collins, Bill Lazier"
goodreads_link = "https://www.goodreads.com/book/show/55270310-be-2-0-beyond-entrepreneurship-2-0"

[Book.2]
name = "Good Economics for Hard Times"
author = "Abhijit V. Banerjee, Esther Duflo"
goodreads_link = "https://www.goodreads.com/book/show/51014619-good-economics-for-hard-times"

[Book.3]
name = "Atomic Habits"
author = "James Clear"
goodreads_link = "https://www.goodreads.com/book/show/40121378-atomic-habits"

[Book.4]
name = "Ultra-Processed People"
author = "Chris van Tulleken"
goodreads_link = "https://www.goodreads.com/book/show/62586003-ultra-processed-people"

[Book.5]
name = "Wordslut"
author = "Amanda Montell"
goodreads_link = "https://www.goodreads.com/book/show/41716694-wordslut"

[Book.6]
name = "The Martian"
author = "Andy Weir"
goodreads_link = "https://www.goodreads.com/book/show/18007564-the-martian"

[Book.7]
name = ""
author = ""
goodreads_link = ""

[Book.8]
name = ""
author = ""
goodreads_link = ""

[Book.9]
name = ""
author = ""
goodreads_link = ""

[Book.10]
name = ""
author = ""
goodreads_link = ""

